<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWqkk4hZ\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWqkk4hZ/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerWqkk4hZ.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerWqkk4hZ\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerWqkk4hZ\appAppKernelProdContainer([
    'container.build_hash' => 'Wqkk4hZ',
    'container.build_id' => 'bb7c26e1',
    'container.build_time' => 1758377881,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWqkk4hZ');
